# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mwallage <mwallage@student.42berlin.de>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/22 14:22:58 by mwallage          #+#    #+#              #
#    Updated: 2024/03/24 19:07:56 by mwallage         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CPP		:= c++
FLAGS	:= -std=c++98 -Wall -Wextra -Werror
SRC		:= main.cpp \
			AMateria.cpp \
			ICharacter.cpp \
			Character.cpp \
			Ice.cpp \
			Cure.cpp \
			IMateriaSource.cpp \
			MateriaSource.cpp
OBJ		:= $(SRC:.cpp=.o)
HPP		:= AMateria.hpp \
			ICharacter.hpp \
			Character.hpp \
			Ice.hpp \
			Cure.hpp \
			IMateriaSource.hpp \
			MateriaSource.hpp
EXEC	:= Materia

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CPP) $(FLAGS) $^ -o $@

%.o: %.cpp $(HPP)
	$(CPP) $(FLAGS) -c $< -o $@

clean:
	rm -f *.o

fclean: clean
	rm -f $(EXEC)

re: fclean
	make

.PHONY: all, clean, fclean, re
